### ISSUE TITLE
Improving the Navbar

### ISSUE THREAD

**Issue by akshatcoder-hash** [akshatcoder-hash/FOSS-website-new#16]
# Fixing Navbar elements

## Overview
Navbar elements are not properly fixed.

## Description
The elements of the NavBar are not properly fixed, some of them being scattered.

![image](https://user-images.githubusercontent.com/69577224/188948724-5f899a77-7185-4f8a-bff2-e8509bad8b88.png)

## Expected outcomes

The Open Source logo should be placed at the top right and the elements must stick to the top.

## Skills

HTML, CSS

## Possible mentors

[Akshat Sharma](https://github.com/akshatcoder-hash)

## Expected project size

5 hours.

## Difficulty

Easy

**Comment by abitsalihu** [comment]
I would like to help with this issue. :)

**Comment by akshatcoder-hash** [comment]
> I would like to help with this issue. :)

Hey @abitsalihu! This issue is a part of an event called Monsoon Season of Code. You can [Register Here](http://go.dsckiet.com/register) to participate and fix this issue and win some prizes too.

**Comment by akshatcoder-hash** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by ShreyashSriv** [comment]
### **Improving The Nav Bar**
### **Background and Technical Skills.**
I am Shreyash Srivastava I have around a year of experience in HTML CSS and JavaScrptand I am a rookie in REACT JS.
I found about MSOC from my friends in DSC KIet and want to start my open source contributiions.

### What problem are you trying to solve and Your Approach?
I am trying to improve the navbar of the FOSS website by using grid and also fixing it on the top and making it a complementry color to the background to make it look nice and clean
 ### Your Timeline to solve the problem.
9th September - I have already forked the repository and started to look and the issue and it will take around 1 day to fix it.
 ### Your Commitments.
I am commited to give my all in order to solve this issue ASAP.

**Comment by akshatcoder-hash** [comment]
Here you go! @ShreyashSriv

**Comment by akashyap25** [comment]
> > # #16
> > ### I know front end.
> > ### Problem - NavBar needs improvement.
> > ### 9 - 14 September
> 
> @akshatcoder-hash

**Comment by ShreyashSriv** [comment]
@akshatcoder-hash solved it and sent a pull request inform if you want any changes

**Comment by akshatcoder-hash** [comment]
#21 does it  Good work @ShreyashSriv!
