### ISSUE TITLE
Designing the About page

### ISSUE THREAD

**Issue by akshatcoder-hash** [akshatcoder-hash/FOSS-website-new#19]
# Designing the About page

## Overview

The About page needs a proper design with more content added to it.

## Description

More content should be added to the About page with an image other than the logo. A hyperlink to the home page should also be added to the FOSS logo at the top left.

![image](https://user-images.githubusercontent.com/69577224/188953281-249a3328-881e-412f-bf97-e9827ce269a0.png)

## Expected outcomes

An About Us page with proper content and image(if required) with hyperlink to the Home Page.

## Skills

HTML, CSS

## Possible mentors

[Akshat Sgarma](https://github.com/akshatcoder-hash)

## Expected project size

3 hours.

## Difficulty

Medium

**Comment by ArunimaShukla03** [comment]
Hey Akshat! I would love to contribute to this and redesign the About page. I would also like to add what open source promotes and what it is all about rather than just mentioning it vaguely.

**Comment by ArunimaShukla03** [comment]
# Designing the About page

## About Me

I'm Arunima Shukla and I have been programming for almost a year and inculcating Open Source for about 4 months now. I have experience in Python, C, C++, HTML, CSS, and JavaScript. My main area of interest is however back-end web development but I am currently wrapping up with the front-end before moving on to the back-end. I am a member of FOSSC and a part of a community promoting women in technical fields (Women In Tech). You may contact me through my LinkedIn [https://www.linkedin.com/in/arunima-shukla-571a42229](url) or Twitter handle @ArunimaShukla03.

## Issue -

Content yet to be added and the logo not linked to the home page.

## Proposal - 

- Writing a description about Open Source and FOSSCU 
- Moving the logo to the top-left corner with home page hyperlinked to it.
- Designing the footer of the page.

## Timeline - 

**8th September - 9th September**: Solving and adding the proposed solution for the aforenamed issue.

## Commitments -

- I will try my best to submit the project on time.
- In case of any delay, I will inform the mentor beforehand.
- I will solve the issue with the best of my ability.

**Comment by akshatcoder-hash** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by akshatcoder-hash** [comment]
Here you go @ArunimaShukla03!

**Comment by akashyap25** [comment]
> > # #19
> > ### I know front end.
> > ### Problem - Less content as about.
> > ### 9 - 11 September
> 
> @akshatcoder-hash

**Comment by ShreyashSriv** [comment]
### **Designing The About Page**

### **Background and Technical Skills.**
I am Shreyash Srivastava I have around a year of experience in HTML CSS and JavaScript and I am a rookie in REACT JS.
I found about MSOC from my friends in DSC KIet and want to start my open source contributiions.

### What problem are you trying to solve and Your Approach?
Will add a hyperlink to the home page via the FOSS logo and will add links to the other foss communites like discord and github. Redesign the about page with some added graphics

 ### Your Timeline to solve the problem.
11th sep- I have forked the repo, started to look into the issue and will start working on it after being assigned

 ### Your Commitments.
I am commited to give my all in order to solve this issue ASAP.

**Comment by akshatcoder-hash** [comment]
Hey @ShreyashSriv! This issue is covered by #25. You can look for other issues or Open your own issues.

**Comment by akshatcoder-hash** [comment]
This solves it #25
